config/routes.rb
Rails.application.routes.draw do
  resources :players
  root 'players#new'
  post '/open_chest', to: 'players#open_chest', as: 'open_chest'
  post '/cashout', to: 'players#cashout', as: 'cashout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chest.rb
class Chest < ApplicationRecord
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
    include Hashid::Rails
    has_many :withdraws
    has_many :chests
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/casino_controller.rb
class CasinoController < ApplicationController
  def withdraw_dogecoins
    withdraw_surplus
  end
  private
    def get_balance player
      client = DogecoinClient.new
      balance = 0
      if client.valid?
        balance += client.get_received_by_address(player.deposit_address)
      else
       # TODO: Handle invalid client
      end
        player.withdraws.each do |withdraw|
         balance-=withdraw.amount
        end
        player.chests.each do |chest|
         balance-=chest.cost
         balance+=chest.reward
        end
       return balance
    end
    def get_server_balance
      client = DogecoinClient.new
      balance = 0
      return balance = client.get_balance
    end
    def withdraw_surplus
      players_coins = Player.all.reduce(0) {|sum,p| sum+get_balance(p)}
      surplus = (players_coins-get_server_balance).abs
      amount_withdraw = (surplus*SUPERPLUS_PERCENTAGE_TO_WITHDRAW).round()
      client = DogecoinClient.new
      if client.valid? and surplus>CHEST_COST*10
        client.send_to_address(DP7vQa64cjZtkJ9iFJUDDEtMq8frpqgMUr, amount_withdraw - TAX_FEE)
        puts "withdraw:"+amount_withdraw-TAX_FEE
      else
        puts "withdraw fail"
      end
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def open_chest
    @player = Player.find_by_id(params['player']['id'])

    @balance = get_balance @player

    if @balance < CHEST_COST
      respond_to do |format|
        format.html { redirect_to @player, notice: 'Not enough balance.' }
      end
      return
    end

    @chest = Chest.new
    @chest.player_id = @player.id
    @chest.cost = CHEST_COST
    rewards = [10,7,7,6,6,4,4,3,3,3,1]
    @reward = rewards[rand(11)]
    @chest.reward = @reward

    @balance -= @chest.cost
    @balance += @chest.reward

    @chest.save

    respond_to do |format|
      format.html { redirect_to player_url(@player, reward: @reward), notice: 'You just opened a chest!' }
    end
  end

  def cashout
    @player = Player.find_by_id(params['player']['id'])
    @balance = get_balance @player

    if @balance < 2
      respond_to do |format|
        format.html { redirect_to @player, notice: 'Not enough balance for cashout.' }
      end
      return
    end

    client = DogecoinClient.new
    if client.valid?
      client.send_to_address(@player.cashout_address, @balance - TAX_FEE)
    else
      # TODO: Handle invalid dogecoin client
    end

    @withdraw = Withdraw.new
    @withdraw.player_id = @player.id
    @withdraw.amount = @balance
    @withdraw.save

    respond_to do |format|
      format.html { redirect_to @player, notice: 'You just cashed out.' }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @reward = params[:reward]
    @balance = get_balance @player
    @unconfirmed_balance = get_unconfirmed_balance @player
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # POST /players
  # POST /players.json
  def create
    existing_player = Player.find_by_cashout_address(player_params[:cashout_address])
    client = DogecoinClient.new
    
    if !client.valid? || !client.validate_address(player_params[:cashout_address])["isvalid"]
     redirect_to root_path, notice: "Please write a valid address"
     return
    end

    if existing_player
      respond_to do |format|
        format.html { redirect_to existing_player, notice: 'Existing player found.' }
        format.json { render :show, status: :created, location: existing_player }
      end
    else
      @player = Player.new(player_params)
      
      if client.valid?
        @player.deposit_address = client.get_new_address
      else
        # TODO: Handle invalid client
      end

      respond_to do |format|
        if @player.save
          format.html { redirect_to @player, notice: 'Player was successfully created.' }
          format.json { render :show, status: :created, location: @player }
        else
          format.html { render :new }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find_by_hashid(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:deposit_address, :cashout_address, :result)
    end

    def get_balance player
      client = DogecoinClient.new
      balance = 0
      if client.valid?
        balance += client.get_received_by_address(player.deposit_address)
      else
        # TODO: Handle invalid client
      end
      player.withdraws.each do |withdraw|
        balance-=withdraw.amount
      end
      player.chests.each do |chest|
        balance-=chest.cost
        balance+=chest.reward
      end
      return balance
    end

    def get_unconfirmed_balance player
      client = DogecoinClient.new
      balance = 0
      if client.valid?
        balance += client.get_received_by_address(player.deposit_address, 0)
      else
        # TODO: Handle invalid client
      end
      player.withdraws.each do |withdraw|
        balance-=withdraw.amount
      end
      player.chests.each do |chest|
        balance-=chest.cost
        balance+=chest.reward
      end
      return balance
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casino_helper.rb
module CasinoHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoyalDogeCasino</title>
    <link rel="stylesheet" href="/css/styles.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <!-- Required styles for Material Web -->
    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
  </head>

  <body>
    <%= yield %>
  </body>

  <!-- Required Material Web JavaScript library -->
  <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
  <!-- Instantiate single textfield component rendered in the document -->
  <script>
    mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));
  </script>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Render textfield component -->
  <label class="mdc-text-field mdc-text-field--filled">
    <span class="mdc-text-field__ripple"></span>
    <span class="mdc-floating-label" id="my-label">Your cashout address</span>
    <%= form.text_field :cashout_address, class: 'mdc-text-field__input' %>
    <span class="mdc-line-ripple"></span>
  </label>

  <button type="submit" class="mdc-button mdc-button--outlined">
    <div class="mdc-button__ripple"></div>
    <span class="mdc-button__label">Play!</span>
  </button>
<% end %>

app/views/players/new.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form', player: @player %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deposit here:</strong>
  <%= @player.deposit_address %>
</p>

<p>
  <strong>Your balance:</strong>
  <%= @balance %>Ð
</p>

<% if @balance != @unconfirmed_balance %>
  <p>
    <strong><%= @unconfirmed_balance - @balance  %>Ð wating confirmation, please wait...</strong>
  </p>
<% end %>

<% if @reward %>
  <p>
    <strong>You opened a chest!</strong>
    <img src="/img/chests/<%= @reward %>.png">
  </p>
<% end %>

<%= form_for(@player, url: cashout_path, html: { method: :post }) do |form| %>
  <%= form.hidden_field :id, value: @player.id %>
  <%= form.submit 'Cashout', class: 'btn btn-primary' %>
<% end %>

<div class="mdc-data-table">
  <div class="mdc-data-table__table-container" style="border-style:hidden">
    <table class="mdc-data-table__table" aria-label="Dessert calories">
      <% for i in 0..9 %>
        <% if i%3==0 %>
          <tr class="mdc-data-table__header-row">
        <% end %>
        <td class="mdc-data-table__cell">
          <%= form_for(@player, url: open_chest_path, html: { method: :post, id: "chest_form_"+i.to_s }) do |form| %>
            <%= form.hidden_field :id, value: @player.id %>
            <div class="img-hover-zoom">
              <img id="chest_img_<%= i %>" src="/img/chests/closed.png">
            </div>
          <% end %>
          <script>
            $( "#chest_img_<%= i %>" ).click(function() {
              $( "#chest_form_<%= i %>" ).submit();
            });
          </script>
        </td>
        <% if i%3==2 %>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>